#!/bin/bash
# we will ffmpeg to convert images to webp

# if $1 is --help or -h output help
if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
  echo "Usage: webp_convert.sh [input file] [output file], if no output file is given, the output file will be the same as the input file with the extension changed to .webp"
  exit 0
fi

# check if ffmpeg is installed
if ! [ -x "$(command -v ffmpeg)" ]; then
  echo 'Error: ffmpeg is not installed.' >&2
  exit 1
fi

# check $1 is given and is a file
if ! [ -f "$1" ]; then
  echo 'Error: Input file does not exist.' >&2
  exit 1
fi

# convert with ffmpeg and save to $2 if given, otherwise save to $1 with .webp extension
if [ "$2" ]; then
  ffmpeg -i $1 $2
else
  ffmpeg -i $1 ${1%.*}.webp
fi
